# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XAIiHvfmVUlF4o2gmw4Lr4J4FPz6Wv8O

# Customer Lifetime Value (CLV) Analysis
## Overview
Customer Lifetime Value (CLV) is a critical metric for businesses to understand the long-term value of their customers. It represents the total revenue a customer is expected to generate over their entire relationship with the business. By accurately calculating CLV, businesses can identify high-value customers, prioritize marketing efforts, and optimize customer retention strategies.

In this notebook, we will perform a comprehensive analysis of CLV using transaction data from an online retail store. We will follow a step-by-step process to calculate CLV for each customer and gain insights into customer segmentation, revenue trends, and opportunities for revenue growth.

## Data Description
The dataset used in this analysis is the Online Retail II dataset from Kaggle. It contains transaction records for a UK-based online retail store between 01/12/2009 and 09/12/2011. The dataset includes information such as InvoiceNo, Quantity, UnitPrice, CustomerID, and more.

## Objectives

### CLV Calculation:
Calculate CLV for each customer using their transaction history and relevant metrics.

### Segmentation:
Segment customers based on their CLV to identify high-value, medium-value, and low-value customers.

### Insights and Recommendations:
Analyze the results to gain insights into customer behavior, revenue trends, and opportunities for revenue growth. Provide recommendations for targeted marketing efforts and customer retention strategies.

## Calculate Customer Lifetime Value (CLV)

- Import neccesarry dependecies
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""- Load dataset"""

# Loading the data with specified encoding
df = pd.read_csv("C:/Users/obypa/OneDrive/Drive/Data Science Portfolio/CRM analysis/cleanedCRM_data.csv", encoding='latin1')
print(df.head())

# Convert 'InvoiceDate' to datetime format
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')

"""- Define a function to calculate CLV"""

import pandas as pd

def calculate_clv(df):
    """
    Calculate Customer Lifetime Value (CLV) for each customer based on their transaction history.

    Parameters:
    - df (DataFrame): DataFrame containing transaction data with columns 'CustomerID', 'InvoiceNo', 'Quantity', and 'UnitPrice'.

    Returns:
    - DataFrame: DataFrame containing CLV for each customer.
    """
    # Calculate revenue per transaction
    df['Revenue'] = df['Quantity'] * df['Price']

    # Aggregate total revenue per customer
    total_revenue_per_customer = df.groupby('Customer ID')['Revenue'].sum()

    # Calculate average purchase frequency per customer
    purchase_frequency_per_customer = df.groupby('Customer ID')['Invoice'].nunique() / df['Customer ID'].nunique()

    # Calculate customer lifetime
    customer_lifetime = (df.groupby('Customer ID')['InvoiceDate'].max() - df.groupby('Customer ID')['InvoiceDate'].min()).dt.days

    # Calculate CLV using simple formula: CLV = Total Revenue * Purchase Frequency * Customer Lifetime
    clv = total_revenue_per_customer * purchase_frequency_per_customer * customer_lifetime

    return clv

def segment_customers_by_clv(clv):
    """
    Segment customers into high-value, medium-value, and low-value segments based on CLV.

    Parameters:
    - clv (Series): Series containing CLV for each customer.

    Returns:
    - DataFrame: DataFrame containing segmentation results with columns 'CustomerID' and 'Segment'.
    """
    # Define criteria for segmentation
    high_value_threshold = clv.quantile(0.75)
    low_value_threshold = clv.quantile(0.25)

    # Segment customers based on CLV
    segment = pd.cut(clv, bins=[-float('inf'), low_value_threshold, high_value_threshold, float('inf')], labels=['Low-Value', 'Medium-Value', 'High-Value'])

    # Create DataFrame to store segmentation results
    segmentation_results = pd.DataFrame({'Customer ID': clv.index, 'Segment': segment})

    return segmentation_results

# Calculate CLV for each customer
clv = calculate_clv(df)

# Segment customers based on CLV
segmentation_results = segment_customers_by_clv(clv)

# Display the segmentation results
print(segmentation_results.head())

"""- Display segmentation/ chart to show customer segments based on their CLV"""

# Count the number of customers in each segment
segment_counts = segmentation_results['Segment'].value_counts()

# Plot the distribution of customers by segment as a pie chart
plt.figure(figsize=(8, 6))
plt.pie(segment_counts, labels=segment_counts.index, autopct='%1.1f%%', colors=['lightcoral', 'lightskyblue', 'lightgreen'])
plt.title('Proportion of Customers by Segment')
plt.show()

"""## Recommendations based on the segmentation results:

- Targeted Marketing for High-Value Customers:

  - Given that high-value customers represent a smaller proportion of the customer base but contribute significantly to revenue, it's crucial to prioritize them in marketing efforts.
  - Offer personalized incentives, exclusive discounts, and rewards programs to encourage repeat purchases and foster loyalty among high-value customers.
  - Send targeted email campaigns with product recommendations based on past purchases to enhance the shopping experience and increase engagement.
  - Consider providing VIP customer service to high-value customers, such as expedited shipping, dedicated support channels, and early access to new products or promotions.

- Medium-Value Customers:

  - Medium-value customers represent a sizable portion of the customer base and have the potential to become high-value customers with the right incentives.
  - Implement targeted marketing strategies to encourage medium-value customers to increase their spending and frequency of purchases.
  - Offer tiered loyalty programs where customers can unlock exclusive benefits and rewards as they spend more over time.
  - Leverage data analytics to identify product preferences and interests of medium-value customers and tailor marketing communications accordingly.

- Low-Value Customers:

  - While low-value customers may not contribute significantly to revenue individually, collectively, they still represent a valuable segment of the customer base.
  - Focus on increasing the average order value and purchase frequency of low-value customers through targeted promotions and cross-selling strategies.
  - Offer special discounts or promotions to incentivize low-value customers to make larger purchases or explore additional product categories.
  - Implement strategies to convert low-value customers into medium-value customers by providing exceptional customer service, personalized recommendations, and a seamless shopping experience.

By targeting marketing efforts towards high-value customers while also nurturing medium-value and low-value customers, the company can optimize its marketing ROI and maximize customer lifetime value. Additionally, personalized and targeted marketing strategies tailored to each segment's preferences and behavior can help drive customer engagement, loyalty, and long-term profitability.






"""